config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: NSQA
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-pear-stoat.sh
        container: qc.acc_shaky-cerise-mammoth
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-brown-chihuahua.sh
        container: qc.doc_wheezy-tangerine-mandrill
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-black-stingray.sh
        container: qc.doc_zippy-yellow-lynx
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-malachite-avocet.sh
        container: qc.doc_foggy-aqua-sheepdog
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-saffron-worm.sh
        container: qc.lic_muzzy-ruby-wolverine
  QC.Met:
    repos:
      github.com/HPCI-Lab/yProv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cinnabar-tarsier.sh
        container: qc.met_hilly-pear-bloodhound
      github.com/HPCI-Lab/yProv validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.surly-gamboge-mist.sh
        container: qc.met_shaggy-tomato-uguisu
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-cinnabar-giraffe.sh
        container: qc.sec_craggy-dandelion-eleuth
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-zucchini-zebra.sh
        container: qc.sty_scaly-yellow-fly
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-vermilion-ferret.sh
        container: qc.sty_lousy-alizarin-dachsbracke
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-razzmatazz-burmese.sh
        container: qc.sty_wiggy-buff-avocet
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-magnolia-woodpecker.sh
        container: qc.uni_zippy-amber-buzzard
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-tan-shark.sh
        container: qc.ver_whiny-fuchsia-burmese
timeout: 5400
