config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-turquoise-giraffe.sh
        container: qc.acc_ready-smalt-kangaroo
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-burgundy-horse.sh
        container: qc.doc_hilly-salmon-wrasse
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-denim-worm.sh
        container: qc.doc_breezy-green-frise
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-maroon-mongrel.sh
        container: qc.doc_clammy-auburn-toad
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-gamboge-coati.sh
        container: qc.lic_geeky-zucchini-lion
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-tangerine-alligator.sh
        container: qc.sec_flabby-pink-lobster
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-teal-dachshund.sh
        container: qc.sty_grumpy-beige-mouse
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-myrtle-crocodile.sh
        container: qc.sty_sleepy-silver-kingfisher
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-maroon-seal.sh
        container: qc.sty_lumpy-gamboge-fish
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-eggplant-iguana.sh
        container: qc.uni_greasy-platinum-frigatebird
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-bistre-buffalo.sh
        container: qc.ver_skinny-amethyst-grasshopper
timeout: 5400
