config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-emerald-lobster.sh
        container: qc.acc_smelly-peach-bulldog
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-brass-havanese.sh
        container: qc.doc_squeaky-tomato-zorse
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-asparagus-gerbil.sh
        container: qc.doc_snappy-brown-whale
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-taupe-tetra.sh
        container: qc.doc_scaly-cinnabar-chimpanzee
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-puce-bat.sh
        container: qc.lic_surly-celadon-snake
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-cyan-wildebeest.sh
        container: qc.sec_crabby-pear-seal
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-firebrick-snail.sh
        container: qc.sty_baggy-orchid-turtle
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-orchid-wolfhound.sh
        container: qc.sty_scanty-indigo-buffalo
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-cerulean-shrimp.sh
        container: qc.sty_snippy-bistre-shrew
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-mauve-flounder.sh
        container: qc.uni_nerdy-rust-chamois
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-orchid-mammoth.sh
        container: qc.ver_scaly-brass-turkey
timeout: 5400
