config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-lime-boar.sh
        container: qc.acc_thirsty-indigo-ray
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-ecru-quetzal.sh
        container: qc.doc_seedy-burgundy-cockroach
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-smalt-dolphin.sh
        container: qc.doc_stealthy-denim-capybara
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-thistle-crane.sh
        container: qc.doc_bluesy-teal-insect
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-russet-goat.sh
        container: qc.lic_skimpy-zucchini-eleuth
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-champagne-dragon.sh
        container: qc.sec_ugly-brown-turtle
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-amethyst-cassowary.sh
        container: qc.sty_shabby-viridian-ibis
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-plum-cichlid.sh
        container: qc.sty_frumpy-alizarin-beagle
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cinnamon-slug.sh
        container: qc.sty_lanky-viridian-abyssinian
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-silver-macaque.sh
        container: qc.uni_pretty-beige-newt
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-ruby-ant.sh
        container: qc.ver_tasty-cerulean-mastiff
timeout: 5400
