config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: sqa
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-fuchsia-tarsier.sh
        container: qc.acc_sunny-gold-greyhound
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-harlequin-rat.sh
        container: qc.doc_gamy-mauve-millipede
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ochre-fly.sh
        container: qc.doc_shaggy-cream-ray
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-black-gecko.sh
        container: qc.doc_hilly-turquoise-toucan
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-asparagus-camel.sh
        container: qc.lic_snazzy-magenta-owl
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.homey-maroon-penguin.sh
        container: qc.sec_stuffy-emerald-woodlouse
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-olive-eel.sh
        container: qc.sty_ugly-heliotrope-ant
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-dandelion-ferret.sh
        container: qc.sty_crabby-goldenrod-chimpanzee
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-salmon-numbat.sh
        container: qc.sty_tasty-coral-jackal
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.homey-saffron-opossum.sh
        container: qc.uni_flimsy-fuchsia-javanese
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-tan-bear.sh
        container: qc.ver_seedy-bronze-neanderthal
timeout: 5400
