config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: sqa
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-vermilion-turkey.sh
        container: qc.acc_gamy-orange-dollar
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-viridian-fox.sh
        container: qc.doc_greasy-eggplant-antelope
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-platinum-gerbil.sh
        container: qc.doc_craggy-pear-neanderthal
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-salmon-rattlesnake.sh
        container: qc.doc_goopy-heliotrope-bat
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-copper-bullfrog.sh
        container: qc.lic_nerdy-ochre-collie
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-sapphire-alligator.sh
        container: qc.sec_tacky-viridian-turtle
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-seashell-orangutan.sh
        container: qc.sty_pasty-eggplant-setter
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-coral-seahorse.sh
        container: qc.sty_ready-asparagus-cichlid
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-cardinal-hound.sh
        container: qc.sty_breezy-amber-seal
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-silver-gorilla.sh
        container: qc.uni_scummy-corn-bordeaux
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-linen-gecko.sh
        container: qc.ver_stuffy-crimson-raccoon
timeout: 5400
