config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-peach-chipmunk.sh
        container: qc.acc_seedy-khaki-caracal
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-saffron-dugong.sh
        container: qc.doc_lumpy-platinum-bandicoot
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-orange-giraffe.sh
        container: qc.doc_baggy-cardinal-tzu
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-burgundy-tetra.sh
        container: qc.doc_lumpy-olivine-coyote
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cyan-rhinoceros.sh
        container: qc.lic_gummy-taupe-lizard
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-carmine-spoonbill.sh
        container: qc.sec_greasy-rust-toucan
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.homey-sapphire-sloth.sh
        container: qc.sty_freaky-cornflower-magpie
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-viridian-newfoundland.sh
        container: qc.sty_shabby-beige-indri
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.surly-cream-hare.sh
        container: qc.sty_homely-fuchsia-javanese
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-emerald-chameleon.sh
        container: qc.uni_homely-gold-cassowary
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-pear-capuchin.sh
        container: qc.ver_seedy-aquamarine-dragonfly
timeout: 5400
