config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-khaki-labradoodle.sh
        container: qc.acc_thirsty-red-gorilla
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-cobalt-crocodile.sh
        container: qc.doc_woolly-malachite-olm
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-plum-crocodile.sh
        container: qc.doc_foggy-green-shark
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-goldenrod-lion.sh
        container: qc.doc_flabby-copper-macaw
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-eggplant-lizard.sh
        container: qc.lic_messy-zucchini-tamarin
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-amethyst-cassowary.sh
        container: qc.sec_chewy-zucchini-moorhen
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-razzmatazz-mole.sh
        container: qc.sty_woolly-malachite-chicken
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-blue-gecko.sh
        container: qc.sty_pokey-pink-chinchilla
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-turquoise-penguin.sh
        container: qc.sty_craggy-taupe-urchin
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-alizarin-civet.sh
        container: qc.uni_chewy-yellow-vulture
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-grey-numbat.sh
        container: qc.ver_nerdy-thistle-turkey
timeout: 5400
