config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-red-jaguar.sh
        container: qc.acc_bumpy-wheat-budgerigar
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-amaranth-newfoundland.sh
        container: qc.doc_zippy-brass-zonkey
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-charcoal-anteater.sh
        container: qc.doc_woozy-platinum-dalmatian
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-tan-uguisu.sh
        container: qc.doc_sickly-violet-spider
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-puce-labradoodle.sh
        container: qc.lic_tasty-sapphire-kudu
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-cobalt-whippet.sh
        container: qc.sec_thirsty-magnolia-caracal
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-yellow-rat.sh
        container: qc.sty_slimy-carmine-tamarin
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-lavender-leopard.sh
        container: qc.sty_baggy-cerise-kudu
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-chartreuse-chinook.sh
        container: qc.sty_silly-sapphire-bombay
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-khaki-caracal.sh
        container: qc.uni_breezy-cobalt-chimpanzee
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.surly-mauve-uguisu.sh
        container: qc.ver_homey-thistle-deer
timeout: 5400
