config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-wheat-cassowary.sh
        container: qc.acc_jumpy-tomato-gerbil
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-scarlet-cattle.sh
        container: qc.doc_nerdy-peach-vole
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-purple-dolphin.sh
        container: qc.doc_sleazy-cerulean-warthog
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-harlequin-spider.sh
        container: qc.doc_scaly-lemon-dunker
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-cyan-wolfhound.sh
        container: qc.lic_snazzy-cobalt-nightingale
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-wheat-dalmatian.sh
        container: qc.sec_jumpy-magnolia-dachshund
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-alizarin-lemur.sh
        container: qc.sty_blurry-vermilion-bracke
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-grey-warthog.sh
        container: qc.sty_homey-razzmatazz-capuchin
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-linen-jackal.sh
        container: qc.sty_skinny-bronze-affenpinscher
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-silver-frigatebird.sh
        container: qc.uni_lovely-periwinkle-serval
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-pumpkin-gopher.sh
        container: qc.ver_whiny-cardinal-bee
timeout: 5400
