config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: NSQA
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-olivine-meerkat.sh
        container: qc.acc_pokey-auburn-cattle
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-smalt-quokka.sh
        container: qc.doc_cheeky-lilac-lemming
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-lilac-akbash.sh
        container: qc.doc_crabby-flax-catfish
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-azure-panda.sh
        container: qc.doc_geeky-emerald-loon
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-heliotrope-toucan.sh
        container: qc.lic_freaky-goldenrod-tapir
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-malachite-orangutan.sh
        container: qc.sec_stuffy-zucchini-mayfly
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-lime-emu.sh
        container: qc.sty_crappy-rose-sloth
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-grey-burmese.sh
        container: qc.sty_squirrely-olivine-mist
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-crimson-urchin.sh
        container: qc.sty_sleazy-pink-stoat
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-alizarin-lobster.sh
        container: qc.uni_trippy-burgundy-dachshund
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-smalt-hyrax.sh
        container: qc.ver_stinky-cinnamon-dogfish
timeout: 5400
