config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.chewy-olive-wildebeest.sh
        container: qc.acc_thirsty-cinnamon-akbash
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-purple-tang.sh
        container: qc.doc_dorky-charcoal-antelope
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-gold-bird.sh
        container: qc.doc_breezy-peach-zorse
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-goldenrod-duck.sh
        container: qc.doc_flabby-sangria-angelfish
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-asparagus-starfish.sh
        container: qc.lic_foggy-sapphire-turkey
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-jade-beaver.sh
        container: qc.sec_sickly-thistle-mongrel
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-jade-capuchin.sh
        container: qc.sty_flabby-crimson-wasp
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.craggy-wisteria-tang.sh
        container: qc.sty_queasy-silver-shrimp
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-purple-coyote.sh
        container: qc.sty_seedy-maroon-urchin
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-blue-lizard.sh
        container: qc.uni_crabby-cornflower-wildebeest
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-periwinkle-cockroach.sh
        container: qc.ver_muggy-smalt-cat
timeout: 5400
