config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-ultramarine-indri.sh
        container: qc.acc_whiny-cyan-monster
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-silver-binturong.sh
        container: qc.doc_craggy-mustard-sponge
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-russet-zebra.sh
        container: qc.doc_chummy-bistre-goose
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-brass-dormouse.sh
        container: qc.doc_lousy-linen-bordeaux
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-plum-numbat.sh
        container: qc.lic_gamy-bistre-bombay
  QC.Met:
    repos:
      github.com/HPCI-Lab/yProv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-cinnamon-greyhound.sh
        container: qc.met_chewy-turquoise-quokka
      github.com/HPCI-Lab/yProv validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-yellow-dog.sh
        container: qc.met_paltry-bronze-dane
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-chocolate-catfish.sh
        container: qc.sec_cheeky-corn-butterfly
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-teal-ostrich.sh
        container: qc.sty_whiny-mauve-dollar
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-tan-earwig.sh
        container: qc.sty_shaggy-olivine-antelope
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-amaranth-badger.sh
        container: qc.sty_beady-goldenrod-ladybird
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-auburn-dachsbracke.sh
        container: qc.uni_seedy-maroon-hippopotamus
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-olive-ant.sh
        container: qc.ver_flaky-green-beetle
timeout: 5400
