config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: sqa
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-chartreuse-owl.sh
        container: qc.acc_cheeky-white-cougar
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-cream-bear.sh
        container: qc.doc_skinny-gamboge-tamarin
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-goldenrod-kingfisher.sh
        container: qc.doc_frumpy-mauve-ladybird
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-viridian-dachsbracke.sh
        container: qc.doc_flaky-rose-moth
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-sangria-mongrel.sh
        container: qc.lic_skanky-plum-maltese
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-salmon-butterfly.sh
        container: qc.sec_sickly-auburn-weasel
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.silly-bronze-tuatara.sh
        container: qc.sty_squirrely-pumpkin-tang
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.skinny-ecru-albatross.sh
        container: qc.sty_snappy-razzmatazz-woodlouse
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.homey-blue-raccoon.sh
        container: qc.sty_dorky-rust-dog
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.surly-copper-barnacle.sh
        container: qc.uni_slimy-crimson-penguin
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-tan-urchin.sh
        container: qc.ver_scummy-denim-tzu
timeout: 5400
