config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-saffron-antelope.sh
        container: qc.acc_lumpy-beige-raccoon
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-taupe-boar.sh
        container: qc.doc_snippy-brown-butterfly
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-turquoise-gorilla.sh
        container: qc.doc_surly-amber-cattle
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-orange-gecko.sh
        container: qc.doc_silly-vermilion-macaque
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-ruby-chameleon.sh
        container: qc.lic_seedy-white-gopher
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-chestnut-gecko.sh
        container: qc.sec_breezy-copper-boar
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-red-shrimp.sh
        container: qc.sty_jumpy-charcoal-termite
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-black-lemming.sh
        container: qc.sty_lousy-bronze-bird
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-amaranth-eagle.sh
        container: qc.sty_crabby-blue-jackal
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.surly-peach-moth.sh
        container: qc.uni_grumpy-saffron-wrasse
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-brass-catfish.sh
        container: qc.ver_messy-scarlet-havanese
timeout: 5400
