config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: sqa
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-champagne-baboon.sh
        container: qc.acc_tacky-vermilion-labradoodle
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-red-quetzal.sh
        container: qc.doc_stinky-crimson-vole
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-charcoal-mouse.sh
        container: qc.doc_frumpy-purple-spider
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-salmon-bordeaux.sh
        container: qc.doc_greasy-malachite-tarsier
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.crappy-tomato-audemer.sh
        container: qc.lic_pasty-tan-toucan
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-coral-kakapo.sh
        container: qc.sec_crappy-denim-mouse
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-lilac-lizard.sh
        container: qc.sty_nerdy-asparagus-corgi
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-puce-goose.sh
        container: qc.sty_silly-green-whippet
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-coral-scorpion.sh
        container: qc.sty_dorky-buff-corgi
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-heliotrope-ostrich.sh
        container: qc.uni_snazzy-azure-drever
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scummy-xanthic-gorilla.sh
        container: qc.ver_pokey-cream-ant
timeout: 5400
