config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-lemon-quail.sh
        container: qc.acc_squeaky-plum-bobcat
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-sangria-tortoise.sh
        container: qc.doc_snazzy-beige-angora
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-yellow-hamster.sh
        container: qc.doc_woozy-lemon-turtle
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-cardinal-toad.sh
        container: qc.doc_tasty-burgundy-dunker
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-periwinkle-retriever.sh
        container: qc.lic_geeky-apricot-peccary
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-brown-flounder.sh
        container: qc.sec_flaky-vermilion-molly
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-gold-camel.sh
        container: qc.sty_goopy-rose-meerkat
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-platinum-whippet.sh
        container: qc.sty_crappy-copper-sparrow
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-teal-dog.sh
        container: qc.sty_nerdy-cobalt-cougar
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.ready-taupe-snail.sh
        container: qc.uni_seedy-scarlet-cassowary
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-champagne-warthog.sh
        container: qc.ver_leaky-seashell-worm
timeout: 5400
