config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: NSQA
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-grey-russel.sh
        container: qc.acc_randy-amethyst-gecko
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-charcoal-meerkat.sh
        container: qc.doc_silly-carmine-molly
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-magenta-toucan.sh
        container: qc.doc_gamy-smalt-spaniel
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-chestnut-dhole.sh
        container: qc.doc_shaggy-heliotrope-cat
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cream-rattlesnake.sh
        container: qc.lic_squeaky-amber-okapi
  QC.Met:
    repos:
      github.com/HPCI-Lab/yProv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-russet-armadillo.sh
        container: qc.met_gimpy-malachite-oriole
      github.com/HPCI-Lab/yProv validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.messy-rust-frise.sh
        container: qc.met_stuffy-mustard-olm
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-puce-mist.sh
        container: qc.sec_squeaky-thistle-dormouse
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.surly-dandelion-loon.sh
        container: qc.sty_squirrely-beige-binturong
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-purple-hedgehog.sh
        container: qc.sty_beady-bronze-drever
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-harlequin-mayfly.sh
        container: qc.sty_chewy-cerise-javanese
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-rust-quokka.sh
        container: qc.uni_stinky-fuchsia-horse
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-peach-gibbon.sh
        container: qc.ver_ready-azure-guppy
timeout: 5400
