config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: NSQA
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-amethyst-chipmunk.sh
        container: qc.acc_stuffy-cyan-lizard
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.homey-cerise-uguisu.sh
        container: qc.doc_wiggy-charcoal-bordeaux
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-harlequin-akbash.sh
        container: qc.doc_boozy-harlequin-dalmatian
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-beige-molly.sh
        container: qc.doc_geeky-amber-flamingo
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-taupe-birman.sh
        container: qc.lic_silly-cardinal-mau
  QC.Met:
    repos:
      github.com/HPCI-Lab/yProv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.hilly-mustard-llama.sh
        container: qc.met_lovely-blue-wallaby
      github.com/HPCI-Lab/yProv validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-indigo-chamois.sh
        container: qc.met_hazy-teal-deer
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-goldenrod-ragdoll.sh
        container: qc.sec_skanky-brass-tapir
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-xanthic-antelope.sh
        container: qc.sty_nerdy-aqua-caterpillar
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-pumpkin-mandrill.sh
        container: qc.sty_snappy-wheat-chamois
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-ecru-dodo.sh
        container: qc.sty_baggy-lilac-caterpillar
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-saffron-caracal.sh
        container: qc.uni_lovely-dandelion-worm
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-cerulean-devil.sh
        container: qc.ver_freaky-chocolate-markhor
timeout: 5400
