config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: NSQA
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.geeky-firebrick-akita.sh
        container: qc.acc_gloppy-chartreuse-donkey
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-brass-greyhound.sh
        container: qc.doc_geeky-magnolia-wasp
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.randy-viridian-molly.sh
        container: qc.doc_pasty-scarlet-bulldog
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-azure-molly.sh
        container: qc.doc_pokey-crimson-cassowary
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.surly-pink-tarsier.sh
        container: qc.lic_bumpy-auburn-sparrow
  QC.Met:
    repos:
      github.com/HPCI-Lab/yProv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.beady-amaranth-devil.sh
        container: qc.met_ugly-wheat-swan
      github.com/HPCI-Lab/yProv validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.sunny-rose-kakapo.sh
        container: qc.met_snappy-firebrick-woodlouse
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-amber-ferret.sh
        container: qc.sec_messy-auburn-toucan
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-cerulean-wolverine.sh
        container: qc.sty_randy-sangria-spider
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-beige-burmese.sh
        container: qc.sty_tacky-olivine-dog
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.zippy-asparagus-vole.sh
        container: qc.sty_messy-wheat-retriever
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.sickly-cyan-cheetah.sh
        container: qc.uni_smelly-celadon-capybara
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-maroon-whippet.sh
        container: qc.ver_lovely-corn-cockroach
timeout: 5400
