config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.frumpy-emerald-rabbit.sh
        container: qc.acc_grumpy-maroon-millipede
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-alizarin-squirt.sh
        container: qc.doc_grumpy-cinnamon-dhole
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-chestnut-chin.sh
        container: qc.doc_shaky-tomato-leopard
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-indigo-caterpillar.sh
        container: qc.doc_homely-bronze-shrimp
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-alizarin-sparrow.sh
        container: qc.lic_greasy-rust-havanese
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.skimpy-tan-collie.sh
        container: qc.sec_sunny-bronze-giraffe
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-amethyst-booby.sh
        container: qc.sty_hilly-cinnamon-birman
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-mauve-gibbon.sh
        container: qc.sty_bluesy-cerise-cockroach
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-dandelion-malamute.sh
        container: qc.sty_jumpy-cinnamon-kingfisher
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.bumpy-puce-kakapo.sh
        container: qc.uni_pretty-apricot-boar
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-silver-ladybird.sh
        container: qc.ver_homey-lilac-impala
timeout: 5400
