config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-burgundy-bullfrog.sh
        container: qc.acc_cheeky-carmine-molly
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.bluesy-smalt-chow.sh
        container: qc.doc_boozy-thistle-saola
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.gloppy-lilac-buzzard.sh
        container: qc.doc_ready-emerald-foxhound
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-lemon-hyena.sh
        container: qc.doc_slaphappy-denim-ragdoll
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-goldenrod-wolverine.sh
        container: qc.lic_skanky-seashell-ostrich
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-silver-turtle.sh
        container: qc.sec_slaphappy-lavender-havanese
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-vermilion-ant.sh
        container: qc.sty_snippy-russet-shark
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-sangria-llama.sh
        container: qc.sty_bluesy-bistre-butterfly
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-denim-dalmatian.sh
        container: qc.sty_tasty-sepia-gopher
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-sangria-mist.sh
        container: qc.uni_pasty-dandelion-lizard
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-aqua-echidna.sh
        container: qc.ver_smelly-brass-cattle
timeout: 5400
