config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: sqa
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-brass-pinscher.sh
        container: qc.acc_crabby-orchid-gar
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-orchid-wombat.sh
        container: qc.doc_paltry-heliotrope-schnauzer
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-ivory-mongrel.sh
        container: qc.doc_droopy-sapphire-macaw
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-red-jackal.sh
        container: qc.doc_leaky-auburn-sheepdog
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-auburn-snake.sh
        container: qc.lic_nippy-cerise-stingray
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.slaphappy-sangria-lemming.sh
        container: qc.sec_seedy-alizarin-wolverine
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-russet-lizard.sh
        container: qc.sty_gummy-goldenrod-angora
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-chartreuse-tarantula.sh
        container: qc.sty_baggy-auburn-scorpion
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-fuchsia-schnauzer.sh
        container: qc.sty_pasty-amethyst-jellyfish
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.homey-teal-markhor.sh
        container: qc.uni_sickly-auburn-baboon
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.jumpy-wheat-kakapo.sh
        container: qc.ver_sleepy-wisteria-paradise
timeout: 5400
