config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: sqa
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-bronze-dragon.sh
        container: qc.acc_muggy-silver-hound
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.grumpy-cerulean-olm.sh
        container: qc.doc_leaky-magenta-llama
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-white-uguisu.sh
        container: qc.doc_snoopy-magnolia-newt
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-purple-whale.sh
        container: qc.doc_skimpy-ecru-hare
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.chummy-malachite-tarantula.sh
        container: qc.lic_leaky-cerise-koala
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.silly-orange-cockroach.sh
        container: qc.sec_grumpy-alizarin-dog
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wiggy-ruby-catfish.sh
        container: qc.sty_scaly-celadon-wildebeest
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-sangria-collie.sh
        container: qc.sty_paltry-lime-lion
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-harlequin-sloth.sh
        container: qc.sty_beady-bronze-tortoise
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-pumpkin-squirrel.sh
        container: qc.uni_ready-aqua-lizard
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-chartreuse-argentino.sh
        container: qc.ver_blurry-amber-angora
timeout: 5400
