config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.woolly-azure-gecko.sh
        container: qc.acc_nerdy-buff-birman
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.leaky-taupe-loon.sh
        container: qc.doc_hilly-silver-dog
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-ultramarine-birman.sh
        container: qc.doc_cheeky-pink-mongrel
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.thirsty-taupe-booby.sh
        container: qc.doc_hazy-razzmatazz-fowl
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-rust-flamingo.sh
        container: qc.lic_flimsy-firebrick-capuchin
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-razzmatazz-dragonfly.sh
        container: qc.sec_sloppy-sangria-terrier
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-smalt-moorhen.sh
        container: qc.sty_ugly-heliotrope-lion
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-cyan-coati.sh
        container: qc.sty_shaky-cerise-quetzal
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.pasty-smalt-woodlouse.sh
        container: qc.sty_gamy-teal-burmese
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-gamboge-tapir.sh
        container: qc.uni_tacky-wisteria-burmese
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-green-quoll.sh
        container: qc.ver_nippy-wisteria-gorilla
timeout: 5400
