config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.foggy-alizarin-warthog.sh
        container: qc.acc_sleazy-taupe-termite
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-emerald-dolphin.sh
        container: qc.doc_seedy-auburn-flounder
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-amaranth-serval.sh
        container: qc.doc_paltry-ruby-zorse
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-cerulean-scorpion.sh
        container: qc.doc_foggy-aqua-starfish
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-indigo-pig.sh
        container: qc.lic_stuffy-red-turkey
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-seashell-numbat.sh
        container: qc.sec_craggy-silver-birman
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-orange-budgerigar.sh
        container: qc.sty_paltry-black-coral
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-blue-bongo.sh
        container: qc.sty_shaky-corn-tzu
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-ruby-woodlouse.sh
        container: qc.sty_flimsy-brown-whippet
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.lumpy-gold-bat.sh
        container: qc.uni_craggy-eggplant-koala
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-mustard-eleuth.sh
        container: qc.ver_nerdy-flax-mammoth
timeout: 5400
