config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-puce-rhinoceros.sh
        container: qc.acc_crabby-beige-chinook
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-crimson-fousek.sh
        container: qc.doc_grumpy-zucchini-forest
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-champagne-jackal.sh
        container: qc.doc_cloudy-corn-harrier
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-teal-manatee.sh
        container: qc.doc_lumpy-smalt-newfoundland
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.trippy-lemon-mongoose.sh
        container: qc.lic_cranky-gold-yak
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-denim-camel.sh
        container: qc.sec_chummy-chestnut-frigatebird
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-fuchsia-balinese.sh
        container: qc.sty_woozy-burgundy-goat
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-seashell-dalmatian.sh
        container: qc.sty_stealthy-alizarin-iguana
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-aqua-mastiff.sh
        container: qc.sty_silly-tangerine-penguin
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.muggy-lilac-llama.sh
        container: qc.uni_pasty-rose-toucan
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-cerulean-kangaroo.sh
        container: qc.ver_sickly-silver-meerkat
timeout: 5400
