config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-black-tapir.sh
        container: qc.acc_dorky-zucchini-foxhound
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cream-bird.sh
        container: qc.doc_skanky-tomato-chipmunk
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.nerdy-grey-monkey.sh
        container: qc.doc_gimpy-russet-corgi
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-cobalt-maltese.sh
        container: qc.doc_flabby-gamboge-kudu
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.fuzzy-platinum-mouse.sh
        container: qc.lic_tacky-persimmon-balinese
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.cozy-maroon-sheepdog.sh
        container: qc.sec_shaky-black-worm
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.pokey-zucchini-terrier.sh
        container: qc.sty_thirsty-magenta-kangaroo
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-magenta-duck.sh
        container: qc.sty_zippy-jade-snail
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-cornflower-chihuahua.sh
        container: qc.sty_snappy-orange-barb
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-crimson-quail.sh
        container: qc.uni_cozy-lavender-burmese
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-seashell-kudu.sh
        container: qc.ver_messy-xanthic-cougar
timeout: 5400
