config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: NSQA
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-tomato-pig.sh
        container: qc.acc_whiny-chartreuse-argentino
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-fuchsia-retriever.sh
        container: qc.doc_lumpy-pumpkin-olm
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-khaki-impala.sh
        container: qc.doc_gimpy-wheat-tzu
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.blurry-orchid-walrus.sh
        container: qc.doc_gamy-cinnabar-tapir
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-olive-stingray.sh
        container: qc.lic_jumpy-goldenrod-rottweiler
  QC.Met:
    repos:
      github.com/HPCI-Lab/yProv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-harlequin-rat.sh
        container: qc.met_hilly-thistle-macaque
      github.com/HPCI-Lab/yProv validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.messy-lilac-stingray.sh
        container: qc.met_breezy-zucchini-fish
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-malachite-jaguar.sh
        container: qc.sec_baggy-mustard-wombat
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-lime-walrus.sh
        container: qc.sty_smelly-teal-bullfrog
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-burgundy-cattle.sh
        container: qc.sty_paltry-tangerine-squirrel
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-charcoal-eagle.sh
        container: qc.sty_freaky-emerald-avocet
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-chartreuse-shrew.sh
        container: qc.uni_sleazy-cornflower-bloodhound
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.droopy-burgundy-reindeer.sh
        container: qc.ver_seedy-rose-schnauzer
timeout: 5400
