config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: sqa
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-sangria-forest.sh
        container: qc.acc_droopy-mustard-deer
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.gamy-linen-spitz.sh
        container: qc.doc_tacky-teal-whippet
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-white-markhor.sh
        container: qc.doc_shabby-mustard-dormouse
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-buff-chow.sh
        container: qc.doc_flabby-puce-urchin
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-copper-dolphin.sh
        container: qc.lic_chewy-asparagus-rottweiler
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.surly-salmon-chimpanzee.sh
        container: qc.sec_chummy-wheat-schnauzer
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-taupe-otter.sh
        container: qc.sty_woozy-azure-forest
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-rose-rottweiler.sh
        container: qc.sty_nerdy-pink-mouse
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-eggplant-bird.sh
        container: qc.sty_bluesy-razzmatazz-shrew
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv pytest:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-cerise-cat.sh
        container: qc.uni_chummy-orchid-cichlid
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-amaranth-rabbit.sh
        container: qc.ver_gloppy-mauve-yak
timeout: 5400
