config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.2.1
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/HPCI-Lab/yProv:
      branch: main
      repo: https://github.com/HPCI-Lab/yProv.git
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-scarlet-guppy.sh
        container: qc.acc_cloudy-puce-coyote
  QC.Doc:
    repos:
      github.com/HPCI-Lab/yProv find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-violet-shark.sh
        container: qc.doc_whiny-turquoise-bison
      github.com/HPCI-Lab/yProv git:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-cinnamon-owl.sh
        container: qc.doc_randy-aquamarine-akita
      github.com/HPCI-Lab/yProv markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.silly-chartreuse-kangaroo.sh
        container: qc.doc_pokey-asparagus-swan
  QC.Lic:
    repos:
      github.com/HPCI-Lab/yProv licensee:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-orange-labradoodle.sh
        container: qc.lic_shaggy-corn-quoll
  QC.Met:
    repos:
      github.com/HPCI-Lab/yProv cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.flimsy-olivine-bear.sh
        container: qc.met_frumpy-silver-greyhound
      github.com/HPCI-Lab/yProv validate_codemeta:
        commands:
        - /usr/bin/env sh .sqa/script.stinky-bronze-birman.sh
        container: qc.met_bluesy-alizarin-deer
  QC.Sec:
    repos:
      github.com/HPCI-Lab/yProv bandit:
        commands:
        - /usr/bin/env sh .sqa/script.lovely-silver-meerkat.sh
        container: qc.sec_sleepy-turquoise-oriole
  QC.Sty:
    repos:
      github.com/HPCI-Lab/yProv flake8:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-orchid-cichlid.sh
        container: qc.sty_freaky-linen-setter
      github.com/HPCI-Lab/yProv hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-lilac-ocelot.sh
        container: qc.sty_muggy-vermilion-crocodile
      github.com/HPCI-Lab/yProv jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-periwinkle-okapi.sh
        container: qc.sty_silly-denim-discus
  QC.Uni:
    repos:
      github.com/HPCI-Lab/yProv commands:
        commands:
        - /usr/bin/env sh .sqa/script.surly-ultramarine-bonobo.sh
        container: qc.uni_dorky-thistle-cassowary
  QC.Ver:
    repos:
      github.com/HPCI-Lab/yProv get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.flabby-cerulean-hound.sh
        container: qc.ver_muggy-yellow-chin
timeout: 5400
